//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodOkuma.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VEGADBEntities : DbContext
    {
        public VEGADBEntities()
            : base("name=VEGADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<F0101D0001TBLDEPOENVANTER> F0101D0001TBLDEPOENVANTER { get; set; }
        public virtual DbSet<F0101TBLBIRIMLEREX> F0101TBLBIRIMLEREX { get; set; }
        public virtual DbSet<F0101TBLSTOKLAR> F0101TBLSTOKLAR { get; set; }
    
        public virtual ObjectResult<find_Result> find(string bar)
        {
            var barParameter = bar != null ?
                new ObjectParameter("bar", bar) :
                new ObjectParameter("bar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<find_Result>("find", barParameter);
        }
    
        public virtual ObjectResult<findStock_Result> findStock(Nullable<int> iND)
        {
            var iNDParameter = iND.HasValue ?
                new ObjectParameter("IND", iND) :
                new ObjectParameter("IND", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findStock_Result>("findStock", iNDParameter);
        }
    
        public virtual ObjectResult<listEnvanter_Result> listEnvanter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listEnvanter_Result>("listEnvanter");
        }
    }
}
